include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_dynamic_calls
    - avoid_final_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - directives_ordering
    - join_return_with_assignment
    - literal_only_boolean_expressions
    - only_throw_errors
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_decorated_box
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties

analyzer:
  exclude:
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

dart_code_metrics:
  metrics-exclude:
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

  rules:
    - avoid-non-null-assertion
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-last
